name: check
on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: nix
    steps:
      - uses: actions/checkout@v4
      - run: nix build .#checks.x86_64-linux.pre-commit-check --print-build-logs
