#!/usr/bin/env bash

session="r5rs"

tmux attach-session -t "$session" || tmux new-session -s "$session" \; \
  split-window -h -t $session \; \
  send-keys -t 1 "nvim -c \"set ft=scheme\"" C-m \; \
  send-keys -t 2 "plt-r5rs --no-prim" C-m \; \
  select-pane -t 1
