#!/usr/bin/env sh

# Reference: https://github.com/mil-ad/polybar-wireguard

connected_interfaces=$(networkctl | grep -P "\d+ .* wireguard routable" -o | cut -d" " -f2)

if [ -n "$connected_interfaces" ];
then
    for interface in $connected_interfaces; do echo "$interface"; done
else
    exit 1
fi
