#!/usr/bin/env bash

session="main"

tmux attach-session -t $session || tmux new-session -s $session \; \
  rename-window task \; \
  send-keys -t 1 "task" C-m \; \
  new-window -n zk \; \
  send-keys -t 2 "nvim $ZK_PATH/index.md" C-m \; \
  new-window -n term \; \
  new-window -n music \; \
  send-keys -t 4 "echo 'TODO: open music player'" C-m \; \
  select-window -t 1 \;
