#!/usr/bin/env bash

# Backup existing password databases and
# database keys (using date in filename date -u
# +%Y-%m-%d_%H-%M-%S)

RCLONE_REMOTE="proton-drive"

for f in "$HOME/doc"/*.{kdbx,kdbx.key}; do
  [ -e "$f" ] || continue
  echo "Backing up $f to $f-$(date -u +%Y-%m-%d_%H-%M-%S)"
  cp "$f" "$f-$(date -u +%Y-%m-%d_%H-%M-%S)"
done

echo "Restoring KeePassXC databases and database keys"
rclone copyto                         \
  "$RCLONE_REMOTE:doc"/ "$HOME/doc/"  \
  --progress                          \
  --include "/*.{kdbx,kdbx.key}"
