#!/usr/bin/env bash

selected_hosts="$(ssh-hosts | fzf -m)"

for host in $selected_hosts; do
    echo "Saving $host"
    directories="$(ssh "$host" ls | fzf -m)"
    for directory in $directories; do
        echo "Saving $host:$directory"
        ssh "$host" "(tar cvzf - ~/$directory)" > "${host}_${directory}.tar.gz"
    done
done
