#!/bin/bash

# Packages to install from Arch repositories
pac_list=(
git
vim
)

# Packages to install from AUR
aurpac_list=(
ttf-iosevka-term-ss08
vim-plug
xbanish
)

install() {
  if pacman -Qi "$1" &> /dev/null; then
    echo ""$1" is already installed"
  else
    echo "Installing " "$1"
    sudo pacman -S --noconfirm --needed "$1"
  fi
}

aurpac() {
  git clone "https://aur.archlinux.org/$1.git" "$HOME/.build/$1"
}

count=0

echo " "
echo "Installing required packages"
echo " "

printf '%s\n' "${pac_list[@]}"

for pac in "${pac_list[@]}" ; do
  count=$[count+1]
  install "$pac";
done

origin="https://git.hektormisplon.xyz/hektor/dots"
git clone "$origin" "$HOME/dots"
cp -r "$HOME/dots/.git" "$HOME/.git"
git --git-dir="$HOME/.git" config --local status.showUntrackedFiles no
git --git-dir="$HOME/.git" stash -m "[dots]"
git --git-dir="$HOME/.git" stash apply
git --git-dir="$HOME/.git" restore "$HOME"

echo " "
echo "Installing aur packages"
echo " "

# [ ] Create aurpac installer function
for package in "${aurpac_list[@]}" ; do
  if pacman -Qi "$1" &> /dev/null; then
    echo "$1 is already installed"
  else
    count=$[count+1]
    aurpac "$package" && makepkg -si -D "$HOME/.build/$package"
  fi
done

echo " "
echo "Setting up NeoVim"
echo " "

git clone --depth=1 https://github.com/savq/paq-nvim.git \
    "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/pack/paqs/start/paq-nvim

## Bluetooth setup
# ___

# - [ ] Check if /etc/pulse/default.pa contains following line
# load-module module-switch-on-connect
